import {ArrowUpRight,Code2,Globe2,Layers3,Palette,ShoppingBag,Workflow} from 'lucide-react';
import {CTA} from '@/components/Site';
import {Reveal} from '@/components/Motion';
import {Badge} from '@/components/ui/badge';
import {Card,CardContent} from '@/components/ui/card';

export const metadata={title:'Services'};
const services=[{icon:Palette,title:'Brand identity',copy:'Naming direction, logos, colour systems and guidelines that give your business a recognisable point of view.'},{icon:Globe2,title:'Web design and development',copy:'Responsive, high-performing websites that make your offer easy to understand and easier to act on.'},{icon:Code2,title:'UI and UX design',copy:'Clear product flows and interfaces shaped around the real needs of your customers and team.'},{icon:ShoppingBag,title:'E-commerce',copy:'Thoughtful storefronts that build trust, reduce friction and help more of the right people buy.'},{icon:Layers3,title:'Campaign design',copy:'Launch concepts, social assets and print-ready creative that keep your message consistent everywhere.'},{icon:Workflow,title:'Digital products',copy:'From first prototype to useful release, we help turn a promising idea into something people can use.'}];
const steps=[['01','Find the signal','We listen, audit and ask the questions that reveal the opportunity.'],['02','Shape the system','We turn the direction into a visual and digital language your team can carry forward.'],['03','Make it real','We design, build, test and launch with enough care to make the final result feel inevitable.']];

export default function Page(){return <main><section className="container py-24 md:py-32"><Reveal><Badge>What we do</Badge><h1 className="mt-6 max-w-5xl text-5xl font-black tracking-[-.06em] md:text-8xl">The thinking and making behind your next chapter.</h1><p className="mt-8 max-w-2xl text-xl leading-8 text-[#b8b8be]">Choose the right starting point or bring us the whole challenge. We build focused teams around the work that matters most.</p></Reveal></section><section className="container pb-28"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map(({icon:Icon,title,copy},index)=><Reveal key={title} delay={index*.06}><Card className="h-full transition duration-300 hover:-translate-y-1 hover:border-[#ffd400]"><CardContent><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#ffd400] text-[#080808]"><Icon size={21}/></div><h2 className="mt-8 text-2xl font-black">{title}</h2><p className="mt-4 leading-7 text-[#b8b8be]">{copy}</p><a href="/contact" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-[#ffd400]">Discuss this service <ArrowUpRight size={16}/></a></CardContent></Card></Reveal>)}</div></section><section className="border-y border-[#303035] bg-[#101014]"><div className="container py-24"><Reveal><p className="text-sm font-bold uppercase tracking-[.2em] text-[#ffd400]">Our process</p><h2 className="mt-4 max-w-2xl text-4xl font-black tracking-[-.04em] md:text-6xl">A clear path from question to outcome.</h2></Reveal><div className="mt-14 grid gap-5 md:grid-cols-3">{steps.map(([number,title,copy],index)=><Reveal key={number} delay={index*.08}><div className="border-t border-[#4a4a50] pt-5"><p className="text-sm font-black text-[#ed168c]">{number}</p><h3 className="mt-10 text-2xl font-black">{title}</h3><p className="mt-4 leading-7 text-[#b8b8be]">{copy}</p></div></Reveal>)}</div></div></section><section className="container py-24"><Reveal><div className="flex flex-col justify-between gap-8 rounded-3xl border border-[#5b4d00] bg-[#2a2200] p-8 md:flex-row md:items-center md:p-12"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#ffd400]">Not sure where to start?</p><h2 className="mt-4 max-w-2xl text-3xl font-black md:text-5xl">A conversation is a perfectly good first brief.</h2></div><CTA/></div></Reveal></section></main>}
