import {ArrowUpRight,FolderKanban,Images,Shapes} from 'lucide-react';
import {CTA} from '@/components/Site';
import {Reveal} from '@/components/Motion';
import {Badge} from '@/components/ui/badge';
import {Card,CardContent} from '@/components/ui/card';

export const metadata={title:'Work'};
const collections=[
  {label:'Branding',slug:'branding',files:['801.jpg','802.jpg','803.jpg','804.jpg','805.jpg','85 BIRTHDAY BANNER.jpg','85 XAMPLE.jpg','C1.jpg','C2.jpg','C4.jpg','C6.jpg','C7.jpg','CUP BRANDING.jpg','bag1.jpg','bag2.jpg']},
  {label:'Flyers',slug:'flyers',files:['ALEXANDER LAUNDRY SERVICES.jpg','CALL TO GLORY.jpg','FB_IMG_1540900566580.jpg','FIRE TERBANACLE.jpg','HOLY GHOST.jpg','IMG_20231016_163920_336.jpg','KRISTY LERE.jpg','OPEN HEAVEN.jpg','REDEEM FLYER.jpg','REDEEM FLYERS PRAISE.jpg','REDEEM.jpg','eagle.jpg']},
  {label:'Letter Heads',slug:'letter-head',files:['DAFNE.jpg','GREEN CODE.jpg','JBC LETTER HEAD.jpg','PEGESUS.jpg','PLAN CONCEPT.jpg','PLURAL DEVELOPMENT.jpg','ZIPS LETTER HEAD.jpg']},
  {label:'Logos',slug:'logos',files:['7 FIGURES.jpg','ADEBOLA OGUNGBE AND CO.jpg','AR.jpg','AUTOTHEFT.jpg','BUTTERFLY.jpg','DIVING LIFE DREAMS.jpg','EONIAN.jpg','FB_IMG_1501187141845.jpg','FB_IMG_1501521333730.jpg','HAULAGE.jpg','Ideal.jpg','JEMEN.jpg','LOGO CONCEPT.jpg','LOGO SAMPLE.jpg','LOGO.jpg','PURPLE.jpg','SAMPLE LOGO.jpg','SAMSONITE.jpg','SMAKE.jpg','TANTUA.jpg','VILLAM.jpg','XOE.jpg','ZIPS.jpg','atmos.jpg','berikon.jpg','claystone.jpg','consupport.jpg','cvilouild.jpg','eglux.jpg','flamboyant.jpg','fleurApex.jpg','hijja.jpg','integride.jpg','lighton.jpg','neuimark.jpg','nueimark 2.jpg','primashoxy.jpg','sealcom.jpg','somitypeters.jpg','vivyafrik.jpg']},
];
const notes=[{icon:Shapes,title:'Identity',copy:'Marks, systems and visual rules that make brands easier to recognise.'},{icon:Images,title:'Campaigns',copy:'Flyers and promotional work made to earn attention in busy places.'},{icon:FolderKanban,title:'Everyday tools',copy:'Letterheads and working assets that keep the brand consistent after launch.'}];

export default function Page(){return <main><section className="container py-24 md:py-32"><Reveal><Badge>Selected work</Badge><h1 className="mt-6 max-w-4xl text-5xl font-black tracking-[-.06em] md:text-8xl">Built for brands with something to say.</h1><p className="mt-8 max-w-2xl text-xl leading-8 text-[#b8b8be]">A living archive of identity systems, campaign artwork, editorial layouts and visual experiments from the studio.</p></Reveal></section><section className="container pb-24"><div className="grid gap-5 md:grid-cols-3">{notes.map(({icon:Icon,title,copy},index)=><Reveal key={title} delay={index*.08}><Card className="h-full"><CardContent><Icon className="text-[#ed168c]" size={24}/><h2 className="mt-7 text-xl font-black">{title}</h2><p className="mt-3 leading-7 text-[#b8b8be]">{copy}</p></CardContent></Card></Reveal>)}</div></section><section className="container space-y-20 pb-28">{collections.map(collection=><section key={collection.slug} aria-labelledby={`${collection.slug}-heading`}><div className="mb-8 flex items-end justify-between gap-4 border-b border-[#303035] pb-4"><h2 id={`${collection.slug}-heading`} className="text-3xl font-black">{collection.label}</h2><p className="text-[#b8b8be]">{collection.files.length} projects</p></div><div className="grid gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-3">{collection.files.map(file=><article key={file} className="group"><div className="aspect-[4/3] overflow-hidden rounded-xl bg-[#17171b]"><img src={encodeURI(`/portfolio/${collection.slug}/${file}`)} alt={`${collection.label} project: ${file.replace(/\.[^.]+$/,'')}`} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" loading="lazy"/></div><h3 className="mt-4 font-bold">{file.replace(/\.[^.]+$/,'')}</h3><p className="mt-1 text-sm text-[#b8b8be]">{collection.label}</p></article>)}</div></section>)}</section><section className="container pb-28"><Reveal><div className="flex flex-col justify-between gap-8 rounded-3xl bg-[#ffd400] p-8 text-[#080808] md:flex-row md:items-center md:p-12"><div><p className="text-sm font-bold uppercase tracking-[.2em]">Have a project in mind?</p><h2 className="mt-4 text-3xl font-black md:text-5xl">Let us add the next case study.</h2></div><CTA/></div></Reveal></section></main>}
