import {ArrowUpRight,Compass,Heart,Lightbulb,Target} from 'lucide-react';
import {CTA} from '@/components/Site';
import {Reveal} from '@/components/Motion';
import {Badge} from '@/components/ui/badge';
import {Card,CardContent} from '@/components/ui/card';

export const metadata={title:'About'};
const principles=[{icon:Compass,title:'Direction over noise',copy:'We ask the useful questions first, then make the answer visible in every detail.'},{icon:Heart,title:'People at the centre',copy:'The best work feels clear to the person using it and true to the people behind it.'},{icon:Lightbulb,title:'Ideas with a job',copy:'Every visual decision should earn its place by making a brand easier to choose.'},{icon:Target,title:'Craft with purpose',copy:'Strategy gets the work moving. Careful execution gets it remembered.'}];

export default function Page(){return <main><section className="container py-24 md:py-32"><Reveal><Badge>About Phintech</Badge><h1 className="mt-6 max-w-5xl text-5xl font-black tracking-[-.06em] md:text-8xl">We make good businesses look as good as they are.</h1><p className="mt-8 max-w-2xl text-xl leading-8 text-[#b8b8be]">Phintech is a creative technology studio in Lagos helping ambitious teams turn a point of view into a brand, a website and a better way to be found.</p></Reveal></section><section className="container pb-28"><Reveal><div className="grid gap-6 md:grid-cols-[1.1fr_.9fr]"><img src="/portfolio/branding/CUP%20BRANDING.jpg" alt="Phintech branding project on a branded cup" className="h-full min-h-80 w-full rounded-2xl object-cover"/><div className="flex flex-col justify-between rounded-2xl border border-[#303035] bg-[#121216] p-8 md:p-10"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#ffd400]">The short version</p><p className="mt-12 text-3xl font-black leading-tight md:text-4xl">Clarity is a creative advantage.</p><p className="mt-6 leading-7 text-[#b8b8be]">When a business knows what it stands for, its brand works harder. We help you find that clarity and turn it into a system your team can actually use.</p></div></div></Reveal></section><section className="border-y border-[#303035] bg-[#101014]"><div className="container py-24"><Reveal><p className="text-sm font-bold uppercase tracking-[.2em] text-[#ffd400]">How we think</p><h2 className="mt-4 max-w-3xl text-4xl font-black tracking-[-.04em] md:text-6xl">Four habits behind the work.</h2></Reveal><div className="mt-12 grid gap-5 sm:grid-cols-2">{principles.map(({icon:Icon,title,copy},index)=><Reveal key={title} delay={index*.07}><Card className="h-full"><CardContent><Icon className="text-[#ed168c]" size={25}/><h3 className="mt-8 text-2xl font-black">{title}</h3><p className="mt-3 leading-7 text-[#b8b8be]">{copy}</p></CardContent></Card></Reveal>)}</div></div></section><section className="container py-24"><Reveal><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#ffd400]">Work with us</p><h2 className="mt-4 max-w-2xl text-4xl font-black tracking-[-.04em] md:text-6xl">Bring the messy bit. We will bring the method.</h2></div><CTA/></div></Reveal></section></main>}
