import {ArrowUpRight,Plus} from 'lucide-react';
import {CTA} from '@/components/Site';
import {Reveal} from '@/components/Motion';
import {Badge} from '@/components/ui/badge';

export const metadata={title:'FAQ',description:'Answers to common questions about working with Phintech Creatives.'};
const questions=[
  ['What kind of projects does Phintech take on?','We work with businesses, founders and teams that need a sharper brand, a better digital experience or creative support for an important launch. That can mean a focused identity project, a website, campaign design or a combination of services.'],
  ['Do you work with clients outside Lagos?','Yes. We are based in Surulere, Lagos and work with clients across Nigeria and beyond. Most of our process is designed to work smoothly through video calls, shared documents and regular progress updates.'],
  ['How long does a project usually take?','A focused identity or campaign can take a few weeks. A website or larger digital product usually needs more time for strategy, design, development and testing. After an initial conversation, we will give you a realistic timeline for your specific scope.'],
  ['What happens after I send an enquiry?','We review the details and reply with a useful next step. That may be a short call, a few clarifying questions or a recommendation for the right starting point. There is no pressure to commit before the work and expectations are clear.'],
  ['Can you work with an existing brand?','Absolutely. We can extend, refine or reorganise an existing identity when a full rebrand is not the right answer. We start by understanding what is already working and where the system is creating friction.'],
  ['How do payments work?','Projects are scoped and agreed before work begins. We typically use an initial deposit to reserve the project and milestone payments for longer engagements. The exact schedule is included in your proposal.'],
  ['Do you provide files and handover support?','Yes. At launch, you receive the agreed final files and a practical handover so your team knows how to use the new assets. Website projects also include the relevant access and launch notes.'],
  ['What should I include in my enquiry?','Tell us what you are trying to achieve, what you have tried so far, your ideal timing and anything that is already fixed. A rough brief is enough; we can shape the rest together.'],
];

export default function Page(){return <main><section className="container py-24 md:py-32"><Reveal><Badge>Questions, answered</Badge><h1 className="mt-6 max-w-4xl text-5xl font-black tracking-[-.06em] md:text-8xl">A little clarity before we begin.</h1><p className="mt-8 max-w-2xl text-xl leading-8 text-[#b8b8be]">Here are the things clients most often ask before starting a project with us.</p></Reveal><div className="mt-16 max-w-4xl">{questions.map(([question,answer],index)=><Reveal key={question} delay={index*.04}><details className="group border-t border-[#303035] py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 text-lg font-black marker:hidden md:text-xl"><span>{question}</span><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-[#4b4b52] text-[#ffd400] transition group-open:rotate-45"><Plus size={18}/></span></summary><p className="max-w-3xl pr-12 pt-5 leading-7 text-[#b8b8be]">{answer}</p></details></Reveal>)}</div></section><section className="container pb-28"><Reveal><div className="flex flex-col justify-between gap-8 rounded-3xl border border-[#5b4d00] bg-[#2a2200] p-8 md:flex-row md:items-center md:p-12"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#ffd400]">Still curious?</p><h2 className="mt-4 text-3xl font-black md:text-5xl">The quickest answer is usually a conversation.</h2></div><CTA/></div></Reveal></section></main>}
